Importing the Dependencies

In [116]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [117]:
# Loading the dataset to a pandas Dataframe
credit_card_dataset = pd.read_csv('creditcard.csv')

In [118]:
# Print first 5 rows of a dataset
credit_card_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [119]:
# Print last 5 rows of a dataset
credit_card_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [120]:
# dataset informations
credit_card_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [121]:
# checking the missing values in each columns
credit_card_dataset.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [122]:
# distribution of legit transactions & fraudulent transactions
credit_card_dataset['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

This Dataset is highly unblanced







0 -->Normal Transaction







1 -->fraudulent Transaction

In [123]:
# separating the data for analysis
legit = credit_card_dataset[credit_card_dataset.Class ==0]
fraud = credit_card_dataset[credit_card_dataset.Class ==1]

In [124]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

In [125]:
# statistical measures of the data(legit)
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [126]:
# statistical measures of the data(fraud)
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [127]:
# compare the value for both transactions
credit_card_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

under - Sampling











Build a sample dataset containing similar distribution of normal transactions and Fraudulent Transactions















Number of Fraudulent Transactions --> 492

In [128]:
legit_sample = legit.sample(n=492)

Concating two Dataframes

In [129]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [130]:
# Print the first 5 rows of a new_dataset
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
278460,168236.0,-1.131382,1.249958,-0.021797,-0.718714,0.280824,-0.231859,-0.190584,-3.049949,0.068810,...,-1.385488,-0.066783,0.385930,-0.045145,-0.791583,-0.011352,-1.027814,-0.123817,1.98,0
250241,154796.0,0.120861,0.730912,-1.681032,-1.551908,3.120142,3.216238,0.364689,0.919473,-0.161562,...,-0.335435,-0.905954,0.110614,0.592915,-0.423961,0.164155,0.245584,0.071025,2.28,0
42585,41162.0,-1.052341,-0.125860,2.685410,-1.552180,-1.152483,0.937935,-0.749185,0.560282,0.460261,...,0.097015,0.734128,-0.397153,-0.389723,0.581107,-0.044458,0.471376,0.182687,30.00,0
121402,76178.0,-0.292729,0.880329,2.031777,0.467258,0.006735,-0.551233,0.908599,-0.283103,-0.343483,...,-0.143983,-0.303464,-0.036211,0.335586,-0.166733,-0.694988,-0.079401,-0.145298,29.98,0
127863,78498.0,-0.502755,0.188666,-0.310252,0.150411,2.424864,3.878252,0.434310,0.892622,-0.499042,...,0.030133,-0.117841,0.126388,0.998568,0.005019,-0.336592,0.137597,0.167856,126.98,0

In [131]:
# print the last 5 rows of a new_dataset
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [132]:
new_dataset['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [133]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,98025.682927,0.054014,-0.103401,-0.050071,-0.019084,0.073978,0.038501,-0.029001,0.144233,0.027105,...,0.022208,0.014076,0.012923,-0.042494,0.024371,-0.002738,0.024178,-0.005987,-0.032382,94.761504
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

Splittting the data into Features & Targets

In [134]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [135]:
print(X)

            Time        V1        V2        V3        V4        V5        V6  \
278460  168236.0 -1.131382  1.249958 -0.021797 -0.718714  0.280824 -0.231859
250241  154796.0  0.120861  0.730912 -1.681032 -1.551908  3.120142  3.216238
42585    41162.0 -1.052341 -0.125860  2.685410 -1.552180 -1.152483  0.937935
121402   76178.0 -0.292729  0.880329  2.031777  0.467258  0.006735 -0.551233
127863   78498.0 -0.502755  0.188666 -0.310252  0.150411  2.424864  3.878252
...          ...       ...       ...       ...       ...       ...       ...
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7        V8        V9  ...       V20       V21       V22  \
278460 -0.190584 -3.049949  0.068810  ...  0.296303 -1.385488 -0.066783
250241  0.364689  0.919473 -0.161562  ...  0.045390 -0.335435 -0.905954
42585  -0.749185  0.560282  0.460261  ...  0.258805  0.097015  0.734128
121402  0.908599 -0.283103 -0.343483  ...  0.085473 -0.143983 -0.303464
127863  0.434310  0.892622 -0.499042  ...  0.400779  0.030133 -0.117841
...          ...       ...       ...  ...       ...       ...       ...
279863 -0.882850  0.697211 -2.064945  ...  1.252967  0.778584 -0.319189
280143 -1.413170  0.248525 -1.127396  ...  0.226138  0.370612  0.028234
280149 -2.234739  1.210158 -0.652250  ...  0.247968  0.751826  0.834108
281144 -2.208002  1.058733 -1.632333  ...  0.306271  0.583276 -0.269209
281674  0.223050 -0.068384  0.577829  ... -0.017652 -0.164350 -0.295135

             V23       V24       V25       V26       V27       V28  Amount
278460  0.385930 -0.045145 -0.791583 -0.011352 -1.027814 -0.123817    1.98
250241  0.110614  0.592915 -0.423961  0.164155  0.245584  0.071025    2.28
42585  -0.397153 -0.389723  0.581107 -0.044458  0.471376  0.182687   30.00
121402 -0.036211  0.335586 -0.166733 -0.694988 -0.079401 -0.145298   29.98
127863  0.126388  0.998568  0.005019 -0.336592  0.137597  0.167856  126.98
...          ...       ...       ...       ...       ...       ...     ...
279863  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00
280143 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76
280149  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89
281144 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00
281674 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53

[984 rows x 30 columns]

In [136]:
print(Y)

278460    0
250241    0
42585     0
121402    0
127863    0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

Split the data into Training data and Test Data

In [137]:
X_train, Y_train, X_test, Y_test = train_test_split(X,Y, test_size=0.2, stratify=Y, random_state=3)

In [138]:
print(X.shape, X_train.shape, X_test.shape)

(984, 30) (787, 30) (787,)

Model Training 











Logistic Regression

In [139]:
model = LogisticRegression()

In [140]:
X = credit_card_dataset.drop(columns='Class', axis=1)
y = credit_card_dataset['Class']     # ✅ 1D array

In [141]:
print(y.shape)

(284807,)

In [142]:
y = y.values.ravel()

In [210]:
from sklearn.model_selection import train_test_split

X = credit_card_dataset.drop(columns='Class', axis=1)
y = credit_card_dataset['Class']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [211]:
print(credit_card_dataset.columns)

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class'],
      dtype='object')

In [212]:
X = credit_card_dataset.drop(columns='Class', axis=1)
y = credit_card_dataset['Class']

In [213]:
y = credit_card_dataset['Class']

In [214]:
print(y.shape)

(284807,)

In [215]:
y = y.values.ravel()

In [216]:
print(y.shape)

(284807,)

In [217]:
y = credit_card_dataset.iloc[:, -1]

In [218]:
print(y.shape)

(284807,)

In [219]:

X = credit_card_dataset.iloc[:, :-1]
y = credit_card_dataset.iloc[:, -1]

In [220]:
y = credit_card_dataset.iloc[:, -1].values.ravel()

In [221]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

credit_card_dataset = pd.read_csv("creditcard.csv")

# Features
X = credit_card_dataset.iloc[:, :-1]

# Target
y = credit_card_dataset.iloc[:, -1].values.ravel()

print(X.shape)
print(y.shape)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LogisticRegression()


print("Model Trained Successfully")

(284807, 30)
(284807,)
Model Trained Successfully

In [222]:
# training the Logistic Regression Model With Training Data
model.fit(X_train, y_train)
 #print("Model Trained Successfully")

/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

Model Evaluation







Accuracy Score

In [157]:
X.shape 
y.shape

(284807,)

In [158]:
print("X Shape:", X.shape)
print("y Shape:", y.shape)

X Shape: (284807, 30)
y Shape: (284807,)

In [159]:
y = credit_card_dataset.iloc[:, :-1].values.ravel()

In [160]:
y = credit_card_dataset.iloc[:, -1]

In [161]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# Load CSV file
dataset = pd.read_csv("creditcard.csv")

# Print dataset shape
print("Dataset Shape:", credit_card_dataset.shape)

# Separate features and target
X = credit_card_dataset.iloc[:, :-1]
y = credit_card_dataset.iloc[:, -1]

# Check shapes
print("X Shape:", X.shape)
print("y Shape:", y.shape)

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=2
)

# Create model
model = LogisticRegression()

# Train model
model.fit(X_train, y_train)

print("Model trained successfully")

Dataset Shape: (284807, 31)
X Shape: (284807, 30)
y Shape: (284807,)
Model trained successfully

/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [162]:
y = y.values.ravel()

In [163]:
y = np.ravel(y)

In [164]:
y = dataset.values.ravel()

In [165]:
X = X.values.ravel()

In [166]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Read CSV file
dataset = pd.read_csv("creditcard.csv")

# Features
X = credit_card_dataset.iloc[:, :-1]

# Target
y = credit_card_dataset.iloc[:, -1]

# Print shapes
print(X.shape)
print(y.shape)

(284807, 30)
(284807,)

In [167]:
X = X.values.ravel()

In [168]:
y = dataset.values.ravel()

In [169]:
X = np.ravel(X)

In [172]:
dataset = dataset.values.ravel()

In [173]:
credit_card_dataset = credit_card_dataset.value_counts()

In [174]:
X = X.values.ravel()

In [175]:
np.ravel(dataset)

array([ 0.00000000e+00, -1.35980713e+00, -7.27811733e-02, ...,
        1.36489143e-02,  2.17000000e+02,  0.00000000e+00],
      shape=(8829017,))

In [224]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# Load dataset
dataset = pd.read_csv("creditcard.csv")

# Features and target
X = dataset.iloc[:, :-1]
y = dataset.iloc[:, -1]

print("X:", X.shape)
print("y:", y.shape)

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Model
model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

print("Success")

X: (284807, 30)
y: (284807,)
Success

/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [181]:
print(dataset.head())
print(dataset.shape)
print(type(dataset))

   Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010

        V26       V27       V28  Amount  Class
0 -0.189115  0.133558 -0.021053  149.62      0
1  0.125895 -0.008983  0.014724    2.69      0
2 -0.139097 -0.055353 -0.059752  378.66      0
3 -0.221929  0.062723  0.061458  123.50      0
4  0.502292  0.219422  0.215153   69.99      0

[5 rows x 31 columns]
(284807, 31)
<class 'pandas.core.frame.DataFrame'>

In [183]:
import pandas as pd

credit_card_dataset = pd.read_csv("creditcard.csv")

print(type(credit_card_dataset))
print(credit_card_dataset.shape)

# safe access
print(credit_card_dataset.iloc[:, 0])

<class 'pandas.core.frame.DataFrame'>
(284807, 31)
0              0.0
1              0.0
2              1.0
3              1.0
4              2.0
            ...
284802    172786.0
284803    172787.0
284804    172788.0
284805    172788.0
284806    172792.0
Name: Time, Length: 284807, dtype: float64

In [225]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [200]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

Y_pred = model.predict(Y_train)

/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [229]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy in testing data",accuracy_score(y_test, y_pred))

Accuracy in testing data 0.9991046662687406

/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [233]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = LogisticRegression()
model.fit(X_train, y_train)

y_train = model.predict(X_train)

print("Accuracy in training data",accuracy_score(y_train, x_pred))

Accuracy in training data 0.9966205095569356

/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(